<?php

/**
 * @OA\Schema(
 *      title="FaceDetectionRequest",
 *      description="Face Detection",
 *      type="object",
 *      required={"image","examId"}
 * )
 */

class FaceDetectionRequest
{
    /**
     * @OA\Property(
     *      title="image",
     *      description="base64 encoded image",
     *      example="/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wgARCAPoAu4DASIAAhEBAxEB/8QAHAABAAEFAQEAAAAAAAAAAAAAAAECAwUGBwQI/8QAGQEBAAMBAQAAAAAAAAAAAAAAAAECAwQF/9oADAMBAAIQAxAAAAHqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw+MzTX5M+w3tPYAAAeJPtYGudc2t3IxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMdyCHUtI0jbctcLh+mevDXklfX7tZ47R2JDi9vs3m1jlOwbTjr0uZnVfLanSclxmi1uqYrUq9e7batTuX13Tb+N268vacNwGzTh7rtWjb0gJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMJ7Pn+FWbnoHH1Wvcq4OkTWISTFmvC9Glyxbn0uu/ksLXSmfm1e8vko8GS8F5x1n3T2bYqzmVmv+fZde2prmxUbDrltGS05dvrE5bPzgVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGtHNcThuo8+2a9sVeV2QVRNKoiIkY/E5DH+p3Jh1bSIZLI6/Xyc2c8eNuVrdplEqGE0q8EZ3rrV7zXWYJm7u2i7XThyQp54AAAAAAAAAAAAAAAAAAAAAAAAAAEa/YwN/QyvowcX6945Xm9Wz4sL1rS968pck5NRJCSEBisZmcN6XbM0unetCyULJpUyv3sd4MOavGee/fnz+Twt7TTKzjb039c+e7M3Ns1/b44KhThAAAAAAAAAAAAAAAAAAAAAAAAAAeP2avOuBmGvuSJUYnL4qtfXtOp53y+fIsZXzxkZ89/KkwViJQmzr+y692dFmaLXd1eijw2tI9tvzVWV0XrsvJjtsp5uXUZ2+a009uEJ1BtVu0a5GexDP0bdzDGX4PpD0fMm02p3Joe5zHpAAAAAAAAAAAAAAAAAAAAAAAAA0ndtIns8CmdPVkSYvJ+SI8uWwOYxrfmJztVk8VdxzzSirzeZTGDvXL6zq1XbOatPV0+h57/AK/RE+S96/VnXHZP1erlwtYvM43PPzz7PTecdf8Aezr5b1alabFOL6db/hrdl8TgN5yWXPxujret6YW+i8lwu2P0o4d1Kcc+YGb5bGa+v37HltG9sU25TVTgAAAAAAAAAAAAAAAAAAAaht+Ano1ZE39iSJVUVQYlkMbWuXuYbKZLtVNWU5mijSOHgv6dayHZh4Nuz2Wy3xeQxlzXszVxXw4TJlQKkStAEokU1W7Th/Nct+r2TBe67aRF23TJT5PZNo1TXOoeLLh82R1Wra27MRltOmoWtm8/o3rpw5zHYhOuQyeuJne1q7l5IAAAAAAAAAAAAAAADx+wnm8ejz292RNpQmJ89+TC05fw1r6fZrOEyw2nSKtuz4tW6V49dz06TjYucvRhFM+x33qrCtNn9GNyPj8UjGoTAiUxIU1JnA2Pfj/R65mirW8xCVSiomAry"
     * )
     *
     * @var string
     */
    public $image;
    /**
     * @OA\Property(
     *      title="exam id",
     *      description="id of exam",
     *      example=1
     * )
     *
     * @var integer
     */
    public $examId;
   

}